// Generated by CoffeeScript 1.10.0
var GeoPoint, SchemaRoller, _kinds, global, ref;

global = (ref = module.exports) != null ? ref : window;

GeoPoint = {
  lat: 0,
  lng: 0
};

_kinds = {};

SchemaRoller = (function() {
  'use strict';
  function SchemaRoller() {
    _kinds = {
      Array: Array,
      Boolean: Boolean,
      Buffer: ArrayBuffer,
      Date: Date,
      GeoPoint: GeoPoint,
      Number: Number,
      Object: Object,
      String: String,
      Function: Function
    };
    this.getClass = function(name) {
      return _kinds[name] || null;
    };
    this.registerClass = function(name, clazz) {
      return _kinds[name] = clazz;
    };
    this.unregisterClass = function(name) {
      if (_kinds.hasOwnProperty(name)) {
        return delete _kinds[name];
      }
    };
  }

  return SchemaRoller;

})();

module.exports.SchemaRoller = new SchemaRoller;

module.exports.SchemaRoller.Vector = require('./vector');

module.exports.SchemaRoller.Schema = require('./schema');
