// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  var SchemaRoller, _global, _kinds, ref,
    slice = [].slice;

  _global = typeof exports !== "undefined" && exports !== null ? exports : window;

  if (typeof Object.assign != 'function') {
    Object.assign = function(target) {
      var index, key, source;
      if (target == null) {
        throw new TypeError('Cannot convert undefined or null to object');
      }
      target = Object(target);
      index = 1;
      while (index < arguments.length) {
        source = arguments[index];
        if (source != null) {
          for (key in source) {
            if (Object.prototype.hasOwnProperty.call(source, key)) {
              target[key] = source[key];
            }
          }
        }
        index = index + 1;
      }
      return target;
    };
  }

    _global.wf = {
    wfUtils: {
      Fun: {},
      Obj: {},
      Str: {}
    }
  };

  _global.wf.wfUtils.Fun.getFunctionName = function(fun) {
    var n;
    if ((n = fun.toString().match(/function+\s{1,}([a-zA-Z_0-9\$]*)/)) != null) {
      return n[1];
    } else {
      return null;
    }
  };
  
  _global.wf.wfUtils.Fun.getConstructorName = function(fun) {
    var name, ref;
    if (fun.constructor.name === 'Function') {
      fun = (ref = fun()) != null ? ref : new fun;
    }
    if ((name = this.getFunctionName(fun.constructor)) != null) {
      return name;
    } else {
      return null;
    }
  };
  
  _global.wf.wfUtils.Fun.construct = function(constructor, args) {
    return new (constructor.bind.apply(constructor, [null].concat(args)));
  };
  
  _global.wf.wfUtils.Fun.factory = _global.wf.wfUtils.Fun.construct.bind(null, Function);
  
  _global.wf.wfUtils.Fun.fromString = function(string) {
    var m;
    if ((m = string.replace(/\n/g, '').replace(/[\s]{2,}/g, '').match(/^function+\s\(([a-zA-Z0-9_\s,]*)\)+\s?\{+(.*)\}+$/)) != null) {
      return _global.wf.wfUtils.Fun.factory([].concat(m[1], m[2]));
    } else {
      if ((m = string.match(new RegExp("^Native::(" + ((Object.keys(this.natives)).join('|')) + ")+$"))) != null) {
        return this.natives[m[1]];
      } else {
        return null;
      }
    }
  };
  
  _global.wf.wfUtils.Fun.toString = function(fun) {
    var s;
    if (typeof fun !== 'function') {
      return fun;
    }
    if (((s = fun.toString()).match(/.*\[native code\].*/)) != null) {
      return "Native::" + (this.getFunctionName(fun));
    } else {
      return s;
    }
  };
  
  _global.wf.wfUtils.Fun.natives = {
    Array: Array,
    ArrayBuffer: ArrayBuffer,
    Boolean: Boolean,
    Buffer: ArrayBuffer,
    Date: Date,
    Number: Number,
    Object: Object,
    String: String,
    Function: Function
  };
  
  _global.wf.wfUtils.Obj.getTypeOf = function(obj) {
    return Object.prototype.toString.call(obj).slice(8, -1);
  };
  
  _global.wf.wfUtils.Obj.isOfType = function(value, kind) {
    return (this.getTypeOf(value)) === (_global.wf.wfUtils.Fun.getFunctionName(kind)) || value instanceof kind;
  };
  
  _global.wf.wfUtils.Obj.objectToQuery = function(object) {
    var i, j, keys, pairs, ref;
    if (object == null) {
      object = {};
    }
    pairs = [];
    keys = Object.keys(object);
    for (i = j = 0, ref = keys.length - 1; 0 <= ref ? j <= ref : j >= ref; i = 0 <= ref ? ++j : --j) {
      pairs[i] = [keys[i], object[keys[i]]];
    }
    return (pairs.map((function(_this) {
      return function(v, k) {
        return v.join('=');
      };
    })(this))).join('&');
  };
  
  _global.wf.wfUtils.Obj.queryToObject = function(string) {
    var o;
    o = {};
    decodeURIComponent(string).replace('?', '').split('&').forEach((function(_this) {
      return function(v, k) {
        var p;
        if ((p = v.split('=')).length === 2) {
          return o[p[0]] = p[1];
        }
      };
    })(this));
    return o;
  };
  
  _global.wf.wfUtils.Str.capitalize = function(string) {
    if (string == null) {
      return '';
    }
	if (typeof string != 'string')
		string = string.toString();
    return "" + (string.charAt(0).toUpperCase()) + (string.slice(1));
  };
  
  _global.wf.wfUtils.Str.stripNull = function(string) {
    if (typeof string === 'undefined') {
      return '';
    }
    return string.replace(/\0/g, '');
  };
  
  _global.wf.wfUtils.Str.regsafe = function(string) {
    if (typeof string === 'undefined') {
      return '';
    }
    console.log( "string: "+string );
    return string.replace(/(\.|\!|\{|\}|\(|\)|\-|\$|\!|\*|\?\[|\])+/g, '\\$&');
  };

  _kinds = {};

  SchemaRoller = (function() {
    function SchemaRoller() {
      var _schemaRef;
      _kinds = {
        Array: Array,
        ArrayBuffer: ArrayBuffer,
        Boolean: Boolean,
        Buffer: ArrayBuffer,
        Date: Date,
        Number: Number,
        Object: Object,
        String: String,
        Function: Function
      };
      this.getClass = (function(_this) {
        return function() {
          var _r, arg, classesOrNames, i, j, len, len1, n, ref;
          classesOrNames = 1 <= arguments.length ? slice.call(arguments, 0) : [];
          for (i = 0, len = classesOrNames.length; i < len; i++) {
            arg = classesOrNames[i];
            if (typeof arg === 'object') {
              if (Array.isArray(arg)) {
                _r = [];
                for (j = 0, len1 = arg.length; j < len1; j++) {
                  n = arg[j];
                  switch (typeof n) {
                    case 'string':
                      _r.push(_this.getClass(n));
                      break;
                    case 'function':
                      _r.push(n);
                      break;
                    default:
                      _r.push(Array.isArray(n) ? _this.getClass.apply(_this, n) : null);
                  }
                }
                return (!(0 <= _r.indexOf(null)) ? {
                  _r: null
                } : void 0);
              }
              return null;
            }
            return (ref = _kinds[arg]) != null ? ref : null;
          }
          return null;
        };
      })(this);
      this.registerClass = function(name, clazz) {
        return _kinds[name] = clazz;
      };
      this.unregisterClass = function(name) {
        if (_kinds.hasOwnProperty(name)) {
          return delete _kinds[name];
        }
      };
      this.listClasses = function() {
        return Object.keys(_kinds);
      };
      this.fromJSON = function(json) {
        switch (typeof json) {
          case 'string':
            return new Schema(JSON.parse(json));
          case 'object':
            return new Schema(json);
        }
        throw new Error("json must be either JSON formatted string or object");
      };
      _schemaRef = {
        type: {
          type: this.listClasses(),
          required: true
        },
        required: 'Boolean',
        extensible: 'Boolean',
        restrict: 'String',
        validate: 'Function',
        "default": '*',
        elements: ['Array', 'Object']
      };
      this.getSchemaRef = function() {
        return _schemaRef;
      };
      this.getDefaults = function() {
        var _def;
        return _def = {
          type: '*',
          required: false,
          extensible: false
        };
      };
    }

    return SchemaRoller;

  })();

  ((ref = typeof module !== "undefined" && module !== null ? module.exports : void 0) != null ? ref : window)['SchemaRoller'] = function() {
    var Schema, SchemaValidator, ValidatorBuilder, Vector, _metaData,
          slice = [].slice;
        
        SchemaValidator = (function() {
          function SchemaValidator(_schema, opts1) {
            var _errorMsg, _o, _oKey, _s, j, l, len, len1, len2, m, obj, ref, ref1, ref2, xKey;
            if (_schema == null) {
              _schema = {};
            }
            this.opts = opts1 != null ? opts1 : {
              extensible: false
            };
            _errorMsg = null;
            this.isValid = function() {
              return _errorMsg || true;
            };
            ref = Object.keys(_schema);
            for (j = 0, len = ref.length; j < len; j++) {
              _oKey = ref[j];
              switch (typeof _schema[_oKey]) {
                case "string":
                  obj = {};
                  obj[_oKey] = {
                    type: _global.wf.wfUtils.Str.capitalize(_schema[_oKey], {
                      required: false
                    })
                  };
                  _o = Object.assign(_schema, obj);
                  _errorMsg = this.validateSchemaEntry(_oKey, _schema[_oKey]);
                  break;
                case "object":
                  if (!Array.isArray(_schema[_oKey])) {
                    if (_oKey !== 'elements') {
                      _errorMsg = this.validateSchemaEntry(_oKey, _schema[_oKey]);
                    } else {
                      ref1 = Object.keys(_schema[_oKey]);
                      for (l = 0, len1 = ref1.length; l < len1; l++) {
                        xKey = ref1[l];
                        if (typeof (_errorMsg = this.validateSchemaEntry(xKey, _schema[_oKey][xKey])) === 'string') {
                          return _errorMsg;
                        }
                      }
                    }
                  } else {
                    ref2 = _schema[_oKey];
                    for (m = 0, len2 = ref2.length; m < len2; m++) {
                      _s = ref2[m];
                      if (typeof _schema[_oKey][_s] === 'string') {
                        _errorMsg = this.validateTypeString(_oKey, _schema[_oKey][_s]);
                      } else {
                        _errorMsg = this.validateSchemaEntry(_oKey, _schema[_oKey][_s]);
                      }
                    }
                  }
                  break;
                case "boolean":
                  _errorMsg = this.validateSchemaEntry(_oKey, _schema[_oKey]);
                  break;
                default:
                  _errorMsg = "value for schema element '" + _oKey + "' was invalid";
              }
            }
            _errorMsg;
          }
        
          SchemaValidator.prototype.validateTypeString = function(key, _type) {
            var e, error;
            if (key.match(/\.?default+$/)) {
              return true;
            }
            if (key.match(/\.restrict+$/)) {
              if (typeof _type !== 'string') {
                return 'restrict requires a Regular Expression String';
              }
              try {
                "text".match(new RegExp(_type));
              } catch (error) {
                e = error;
                if (!_type.match(_schemaroller_.rx)) {
                  return "Regular Expression provided for '" + key + "' was invalid";
                }
              }
            } else if (((_schemaroller_.getClass(_global.wf.wfUtils.Str.capitalize(_type))) != null) === false) {
              return "type '<" + _type + ">' for schema element '" + key + "' was invalid";
            }
            return true;
          };
        
          SchemaValidator.prototype.validateSchemaEntry = function(key, params, opts) {
            var _fn, _keys, _kind, _p, _res, _schemaKeys, _t, _type, e, eMsg, error, item, j, keyPath, l, len, len1, len2, len3, m, n, param, ref, ref1, ref2, ref3, sKey, xKey;
            if (opts == null) {
              opts = this.opts;
            }
            _schemaKeys = _schemaroller_.getSchemaRef();
            if (params == null) {
              return key + " was null or undefined";
            }
            if (typeof params === 'boolean') {
              return true;
            }
            if (typeof params === 'string') {
              return this.validateTypeString("" + key, params);
            }
            if (typeof params === 'object') {
              if (!params.hasOwnProperty("type")) {
                if (Array.isArray(params)) {
                  for (j = 0, len = params.length; j < len; j++) {
                    item = params[j];
                    if (typeof (_res = this.validateSchemaEntry(key, item)) === 'string') {
                      return _res;
                    }
                  }
                } else {
                  if ((_p = (keyPath = key.split('.')).pop()) !== 'elements') {
                    if (_p === 'default') {
                      return true;
                    }
                    return "value for schema element '" + key + "' was malformed. Property 'type' was missing";
                  } else {
                    ref = Object.keys(params);
                    for (l = 0, len1 = ref.length; l < len1; l++) {
                      param = ref[l];
                      _keys = [].concat(keyPath).concat(param);
                      if (typeof (_res = this.validateSchemaEntry("" + (_keys.join('.')), params[param])) === 'string') {
                        return _res;
                      }
                    }
                  }
                }
                return true;
              }
              if ((_schemaroller_.getClass(params.type)) == null) {
                if (params.type === '*') {
                  return true;
                }
                if (Object.keys(params).length === 0) {
                  return true;
                }
                if (typeof params.type === 'object') {
                  return this.validateSchemaEntry(key, params.type);
                }
                if (key.split('.').pop() === 'default') {
                  if (this._defaults == null) {
                    this._defaults = {};
                  }
                  this._defaults[key] = params;
                  return true;
                }
                return "value for schema element '" + key + "' has invalid type '<" + params.type + ">'";
              }
              ref1 = Object.keys(params);
              for (m = 0, len2 = ref1.length; m < len2; m++) {
                sKey = ref1[m];
                if (!((_schemaKeys[sKey] != null) || opts.extensible)) {
                  return "schema element '" + key + "." + sKey + "' is not allowed";
                }
                if (typeof params[sKey] === "string") {
                  _kind = _global.wf.wfUtils.Str.capitalize(params[sKey]);
                  if (sKey === 'restrict') {
                    try {
                      new RegExp(params[sKey]);
                    } catch (error) {
                      e = error;
                      return e;
                    }
                    return true;
                  }
                  if (!((_schemaKeys[sKey] != null) || opts.extensible)) {
                    return "schema element '" + key + "." + sKey + "' is not allowed";
                  }
                  if (typeof (eMsg = this.validateTypeString(key + "." + sKey, params[sKey])) === 'string') {
                    return eMsg;
                  }
                }
                if (typeof _schemaKeys[sKey] === 'object') {
                  if (sKey === "elements") {
                    ref2 = Object.keys(params.elements);
                    for (n = 0, len3 = ref2.length; n < len3; n++) {
                      xKey = ref2[n];
                      if (typeof (eMsg = this.validateSchemaEntry(key + "." + xKey, params.elements[xKey])) === 'string') {
                        return eMsg;
                      }
                    }
                    return true;
                  } else {
                    if ((_type = (ref3 = _schemaKeys[sKey]) != null ? ref3.type : void 0) == null) {
                      return "type attribute was not defined for " + key;
                    }
                    if (!Array.isArray(_type)) {
                      _type = _type.type;
                    }
                  }
                }
              }
              return true;
            } else {
              _t = typeof params;
              if (_t !== 'function') {
                if (_schemaKeys[key.split('.').pop()] !== _global.wf.wfUtils.Str.capitalize(_t)) {
                  return "value for schema element '" + key + "' has invalid type '<" + _t + ">'";
                }
              } else {
                if ((_fn = _global.wf.wfUtils.Fun.getConstructorName(params)) !== _schemaKeys[key]) {
                  return "value for schema element '" + key + "' has invalid class or method '<" + _fn + ">'";
                }
              }
              return true;
            }
            return "unable to process schema element '" + key + "'";
          };
        
          return SchemaValidator;
        
        })();
        
        ValidatorBuilder = (function() {
          function ValidatorBuilder() {
            var _buildValidator, _validators;
            _validators = {};
            _buildValidator = (function(_this) {
              return function(_ref, _path) {
                var _v;
                _v = [_ref];
                if (Array.isArray(_ref)) {
                  _v = _ref.map(function(_s) {
                    return _buildValidator(_s, _path);
                  });
                }
                return _validators[_path] = function(value) {
                  var _x, e, fName, j, k, l, len, len1, ref, vItm, val;
                  for (j = 0, len = _v.length; j < len; j++) {
                    vItm = _v[j];
                    if (vItm.required && !(value != null)) {
                      return "value for '" + _path + "' is required";
                    }
                    switch (typeof value) {
                      case 'string':
                        if (typeof vItm === 'object') {
                          _x = (ref = vItm.type) != null ? ref : null;
                        }
                        if (_x == null) {
                          _x = vItm;
                        }
                        if (!(vItm === 'String' || _x.match(/^string$/i))) {
                          return _path + " requires " + _x + " type 'String'";
                        }
                        if (vItm.restrict != null) {
                          if (((new RegExp(vItm.restrict)).exec(value)) == null) {
                            return "value '" + value + "' for " + _path + " did not match required expression";
                          }
                        }
                        return true;
                      case 'function':
                        _x = typeof vItm === 'string' ? vItm : _global.wf.wfUtils.Fun.getConstructorName(vItm);
                        return _x === _global.wf.wfUtils.Fun.getConstructorName(value);
                      case 'object':
                        if (!Array.isArray(vItm)) {
                          return _validators["" + _path](val);
                          return _validators[_path](val);
                        } else {
                          for (val = l = 0, len1 = value.length; l < len1; val = ++l) {
                            k = value[val];
                            if (typeof (e = _validators[_path](val)) === 'string') {
                              return e;
                            }
                          }
                          return true;
                        }
                        break;
                      case 'number':
                        _x = (vItm.type != null) && typeof vItm.type === 'string' ? _schemaroller_.getClass(vItm.type) : vItm.type;
                        if (_x == null) {
                          _x = vItm;
                        }
                        if (_x === 'Number') {
                          return true;
                        }
                        if ((fName = _global.wf.wfUtils.Fun.getFunctionName(_x)) !== 'Number') {
                          return "'" + _path + "' expected " + fName + ", type was '<Number>'";
                        }
                        return !isNaN(new _x(value));
                      default:
                        _x = typeof vItm.type === 'string' ? _schemaroller_.getClass(vItm.type) : vItm.type;
                        return (_x != null) && value instanceof _x;
                    }
                  }
                  return "unable to validate " + _path;
                };
              };
            })(this);
            this.list = function() {
              return Object.keys(_validators);
            };
            this.get = function(path) {
              var ref;
              return (ref = _validators[path]) != null ? ref : null;
            };
            this.set = function(_path, func) {
              if (!((func != null) && typeof func === 'function')) {
                return "2nd argument expects a function";
              }
              return _validators[_path] = func;
            };
            this.create = function(_ref, _path) {
              return _buildValidator.apply(this, arguments);
            };
            this.exec = function(_path, value) {
              if (!_validators.hasOwnProperty(_path)) {
                return "validator for '" + _path + "' does not exist";
              }
              return _validators[_path](value);
            };
          }
        
          ValidatorBuilder.getInstance = function() {
            return this.__instance != null ? this.__instance : this.__instance = new this;
          };
        
          return ValidatorBuilder;
        
        })();
        
        Vector = (function() {
          'use strict';
          function Vector() {
            var _check, _list, _mdRef, _t, _type, items;
            _type = arguments[0], items = 2 <= arguments.length ? slice.call(arguments, 1) : [];
            _list = [];
            if (!Array.isArray(_type)) {
              _t = typeof _type;
              if (_t === 'string') {
                _type = [_type];
              }
              if (_t.match(/^(function|object)$/)) {
                _type = [_type];
              }
              if (_t === null || _t === 'Function') {
                _type = ['*'];
              }
            }
            _check = function(item) {
              var j, len;
              for (j = 0, len = _type.length; j < len; j++) {
                _t = _type[j];
                if ((typeof _t === 'string') && _t.match(/^(\*|ALL)$/)) {
                  return true;
                }
                if (!(_t = _schemaroller_.getClass(_t))) {
                  return false;
                }
                if (!_global.wf.wfUtils.Obj.isOfType(item, _t)) {
                  return false;
                }
              }
              return true;
            };
            this.validate = (function(_this) {
              return function() {
                var _path, _validator;
                _path = _this.path();
                _validator = ValidatorBuilder.getInstance();
                console.log(ValidatorBuilder.getInstance().list());
                _list.forEach(function(itm) {
                  var e;
                  if (typeof (e = _validator.exec(_path, itm)) === 'string') {
                    return e;
                  }
                });
                return true;
              };
            })(this);
            this.getItemAt = (function(_this) {
              return function(idx) {
                if (_list.length = idx + 1) {
                  return _list[idx];
                } else {
                  return null;
                }
              };
            })(this);
            this.setItemAt = (function(_this) {
              return function(idx, item) {
                if (!_check(item)) {
                  return false;
                }
                _list.splice(idx, 0, item);
                return _this;
              };
            })(this);
            this.removeItemAt = (function(_this) {
              return function(idx, item) {
                if (!(idx <= _list.length)) {
                  return false;
                }
                return _list.splice(idx, 1, item);
              };
            })(this);
            this.replaceAll = (function(_this) {
              return function(array) {
                var itm, j, len;
                _this.reset();
                for (j = 0, len = array.length; j < len; j++) {
                  itm = array[j];
                  _this.addItem(itm);
                }
                return _this;
              };
            })(this);
            this.replaceItemAt = (function(_this) {
              return function(idx, item) {
                if (!_check(item)) {
                  return false;
                }
                if (!(idx <= _list.length)) {
                  return false;
                }
                if (idx <= _list.length) {
                  _list.splice(idx, 1);
                }
                return _this;
              };
            })(this);
            this.addItem = (function(_this) {
              return function(item) {
                return _this.setItemAt(_list.length, item);
              };
            })(this);
            this.shift = (function(_this) {
              return function() {
                return _list.shift();
              };
            })(this);
            this.unshift = (function(_this) {
              return function() {
                var items;
                items = 1 <= arguments.length ? slice.call(arguments, 0) : [];
                items.forEach(function(item) {
                  return _this.setItemAt(0, item);
                });
                return _this;
              };
            })(this);
            this.pop = (function(_this) {
              return function() {
                return _list.shift();
              };
            })(this);
            this.push = (function(_this) {
              return function() {
                var items;
                items = 1 <= arguments.length ? slice.call(arguments, 0) : [];
                items.forEach(function(item) {
                  return _this.addItem(item);
                });
                return _this;
              };
            })(this);
            this.reset = (function(_this) {
              return function() {
                _list = [];
                return _this;
              };
            })(this);
            this.length = (function(_this) {
              return function() {
                return _list.length;
              };
            })(this);
            this.sort = (function(_this) {
              return function(func) {
                _list.sort(func);
                return _this;
              };
            })(this);
            this.valueOf = (function(_this) {
              return function() {
                return _list;
              };
            })(this);
            this.toString = (function(_this) {
              return function() {
                return _list.toString();
              };
            })(this);
            if (items[items.length - 1] instanceof _metaData) {
              _mdRef = items[items.length - 1];
              items.splice(items.length - 1, 1);
            } else {
              _mdRef = new _metaData(this, {
                _path: '',
                _root: this
              });
            }
            this.objectID = (function(_this) {
              return function() {
                return _mdRef.get('_id');
              };
            })(this);
            this.root = (function(_this) {
              return function() {
                return _mdRef.get('_root');
              };
            })(this);
            this.path = (function(_this) {
              return function() {
                return _mdRef.get('_path');
              };
            })(this);
            this.parent = (function(_this) {
              return function() {
                var _root;
                if (!(((_root = _this.root()) != null) instanceof Schema || _root instanceof Vector)) {
                  return null;
                }
                return _root.get(_this.path().split('.').pop().join('.'));
              };
            })(this);
            if (items != null) {
              this.push(items);
            }
          }
        
          return Vector;
        
        })();
        
        Schema = (function() {
          'use strict';
          function Schema(_o, opts) {
            var _getKinds, _hasRequiredFields, _mdRef, _oE, _object, _required_elements, _schema_validator, _validate, _validators, _walkSchema, eMsg, j, len, ref;
            if (_o == null) {
              _o = {};
            }
            if (opts == null) {
              opts = {
                extensible: false
              };
            }
            _object = {};
            _required_elements = [];
            _validators = {};
            if (_o.elements != null) {
              ref = Object.keys(_o.elements);
              for (j = 0, len = ref.length; j < len; j++) {
                _oE = ref[j];
                if ((_o.elements[_oE].required != null) && _o.elements[_oE].required) {
                  _required_elements.push(_oE);
                }
              }
            }
            _hasRequiredFields = (function(_this) {
              return function(obj) {
                var _path, key, l, len1, oKeys;
                oKeys = Object.keys(obj);
                for (l = 0, len1 = _required_elements.length; l < len1; l++) {
                  key = _required_elements[l];
                  _path = (_path = _this.path()).length ? _path : 'root element';
                  if (!(0 <= oKeys.indexOf(key))) {
                    return "required property '" + key + "' is missing for '" + _path + "'";
                  }
                }
                return true;
              };
            })(this);
            _schema_validator = new SchemaValidator(_o, opts);
            if (typeof (eMsg = _schema_validator.isValid()) === 'string') {
              throw eMsg;
            }
            (_walkSchema = (function(_this) {
              return function(obj, path) {
                var _k, item, l, len1, objPath, ref1, results;
                ref1 = (Array.isArray(obj) ? obj : Object.keys(obj));
                results = [];
                for (l = 0, len1 = ref1.length; l < len1; l++) {
                  _k = ref1[l];
                  objPath = (path != null) && 1 <= path.length ? path + "." + _k : _k;
                  ValidatorBuilder.getInstance().create(obj[_k], objPath);
                  if ((obj[_k].hasOwnProperty('elements')) && (typeof obj[_k].elements === 'object')) {
                    if (!Array.isArray(obj[_k].elements)) {
                      results.push(_walkSchema(obj[_k].elements, objPath));
                    } else {
                      results.push((function() {
                        var len2, m, ref2, results1;
                        ref2 = obj[_k].elements;
                        results1 = [];
                        for (m = 0, len2 = ref2.length; m < len2; m++) {
                          item = ref2[m];
                          results1.push(_walkSchema(item, objPath));
                        }
                        return results1;
                      })());
                    }
                  } else {
                    results.push(void 0);
                  }
                }
                return results;
              };
            })(this))(_o.elements || {});
            _validate = function(key, value) {
              var _l, _p, _path, _ref, i, k, l, len1, msg, ref1, ref2;
              if (!(0 <= ((ref1 = ValidatorBuilder.getInstance().list()) != null ? ref1.indexOf(key) : void 0))) {
                _l = ValidatorBuilder.getInstance().list();
                _path = [];
                ref2 = key.split('.');
                for (i = l = 0, len1 = ref2.length; l < len1; i = ++l) {
                  k = ref2[i];
                  _path[i] = k;
                  _p = _path.join('.');
                  if (!(0 <= _l.indexOf(_p))) {
                    _path[i] = '*';
                  }
                }
                if (!(_ref = ValidatorBuilder.getInstance().get(_p))) {
                  if (!opts.extensible) {
                    return "'" + key + "' is not a valid schema property";
                  }
                }
                ValidatorBuilder.getInstance().set(key, _ref);
              }
              if (typeof (msg = ValidatorBuilder.getInstance().exec(key, value)) === 'string') {
                return msg;
              }
              return true;
            };
            _getKinds = (function(_this) {
              return function(_s) {
                var _elems;
                _elems = Object.keys(_s).map(function(key) {
                  if (_s[key].type != null) {
                    return _s[key].type;
                  } else {
                    return null;
                  }
                });
                _elems = _elems.filter(function(elem) {
                  return elem !== null;
                });
                if (_elems.length) {
                  return _elems;
                } else {
                  return null;
                }
              };
            })(this);
            this.get = (function(_this) {
              return function(key) {
                return _object[key];
              };
            })(this);
            this.set = (function(_this) {
              return function(key, value) {
                var _extensible, _f, _key, _kinds, _md, _opts, _s, _schema, k, l, len1, ref1, ref2, ref3, ref4, v;
                if (typeof key === 'object') {
                  if (typeof (_f = _hasRequiredFields(Object.assign({}, _object, key))) === 'string') {
                    return _f;
                  }
                  for (k in key) {
                    v = key[k];
                    eMsg = _this.set(k, v);
                    if (typeof eMsg === 'string') {
                      return eMsg;
                    }
                  }
                } else {
                  _schema = (ref1 = _o.elements) != null ? ref1 : _o;
                  _extensible = _o.extensible != null ? _o.extensible : opts.extensible || false;
                  ref2 = key.split('.');
                  for (l = 0, len1 = ref2.length; l < len1; l++) {
                    k = ref2[l];
                    if ((_schema[k] != null) && _schema[k].hasOwnProperty('extensible')) {
                      _extensible = _schema[k].extensible;
                    }
                    _schema = _schema.elements != null ? _schema.elements[k] : _schema[k];
                    _key = ((ref3 = _this.parent().path()) != null ? ref3.length : void 0) ? (_this.parent().path()) + "." + k : k;
                    if (_schema == null) {
                      if (!_extensible) {
                        return "element '" + k + "' is not a valid element";
                      }
                      _schema = {
                        type: '*',
                        required: true,
                        extensible: false
                      };
                    }
                    if (typeof value === 'object') {
                      if (!Array.isArray(value)) {
                        _opts = {
                          extensible: _extensible
                        };
                        _md = new _metaData(_this, {
                          _path: _key,
                          _root: _this.root()
                        });
                        _s = new Schema((ref4 = _schema.elements) != null ? ref4 : _schema, _opts, _md);
                      } else {
                        if (Array.isArray((_kinds = _getKinds(_schema)))) {
                          _kinds = _kinds.map(function(itm) {
                            switch (typeof itm) {
                              case 'string':
                                return itm;
                              case 'object':
                                if (itm.hasOwnProperty('type')) {
                                  return itm.type;
                                }
                            }
                          });
                          _kinds = _kinds.filter(function(itm) {
                            return itm != null;
                          });
                          _kinds = _kinds.length ? _kinds : '*';
                          _s = new Vector(_kinds || '*', new _metaData(_this, {
                            _path: key
                          }));
                        }
                      }
                      if (!((_schema != null) && (_s != null) && typeof _s === 'object')) {
                        return "'" + key + "' was invalid";
                      }
                      value = _s[_s instanceof Vector ? 'replaceAll' : 'set'](value);
                      if ((typeof value) === 'string') {
                        return value;
                      }
                    } else {
                      if (key !== "_root") {
                        if ((typeof (eMsg = _validate(_key, value))) === 'string') {
                          return eMsg;
                        }
                      }
                    }
                    _object[key] = value;
                  }
                }
                return _this;
              };
            })(this);
            this.validate = (function(_this) {
              return function() {
                var _k, _path, e, l, len1, ref1;
                _path = _this.path();
                ref1 = ValidatorBuilder.getInstance().list();
                for (l = 0, len1 = ref1.length; l < len1; l++) {
                  _k = ref1[l];
                  _path = _path.length > 0 ? _path + "." + _k : _k;
                  if (typeof (e = _validate(_k, _this.root().get(_k))) === 'string') {
                    return e;
                  }
                }
                return true;
              };
            })(this);
            this.has = (function(_this) {
              return function(key) {
                return _object.hasOwnProperty(key);
              };
            })(this);
            this.del = (function(_this) {
              return function(key) {
                if (_this.has(key)) {
                  return delete _object[key];
                }
              };
            })(this);
            this.forEach = (function(_this) {
              return function(iterator, scope) {
                var _results, key;
                _results = [];
                for (key in _object) {
                  if (!_object.hasOwnProperty(key)) {
                    continue;
                  }
                  _results.push(iterator.call(scope, _object[key], key));
                }
                return _results;
              };
            })(this);
            this.keys = (function(_this) {
              return function() {
                var keys;
                keys = [];
                _this.forEach(function(value, key) {
                  return keys.push(key);
                });
                return keys;
              };
            })(this);
            this.valueOf = (function(_this) {
              return function() {
                return _object;
              };
            })(this);
            this.toJSON = (function(_this) {
              return function() {
                var _derive, k, v;
                _o = {};
                _derive = function(itm) {
                  var _arr, k, ref1, val;
                  if (itm instanceof Schema) {
                    return _derive(itm.toJSON());
                  }
                  if (itm instanceof Vector) {
                    _arr = [];
                    ref1 = itm.valueOf();
                    for (k in ref1) {
                      val = ref1[k];
                      _arr.push(_derive(val));
                    }
                    return _arr;
                  }
                  return itm;
                };
                for (k in _object) {
                  v = _object[k];
                  _o[k] = _derive(v);
                }
                return _o;
              };
            })(this);
            this.toString = (function(_this) {
              return function(pretty) {
                if (pretty == null) {
                  pretty = false;
                }
                return JSON.stringify(_this.toJSON(), null, (pretty ? 2 : void 0));
              };
            })(this);
            this.canFreeze = (function(_this) {
              return function() {
                return typeof Object.freeze === 'function';
              };
            })(this);
            this.freeze = (function(_this) {
              return function() {
                if (_this.canFreeze()) {
                  Object.freeze(_this);
                  Object.freeze(_object);
                }
                return _this;
              };
            })(this);
            this.isFrozen = (function(_this) {
              return function() {
                if (_this.canFreeze()) {
                  return Object.isFrozen(_object);
                } else {
                  return false;
                }
              };
            })(this);
            this.canSeal = (function(_this) {
              return function() {
                return typeof Object.seal === 'function';
              };
            })(this);
            this.seal = (function(_this) {
              return function() {
                if (_this.canSeal()) {
                  Object.seal(_this);
                  Object.seal(_object);
                }
                return _this;
              };
            })(this);
            this.isSealed = (function(_this) {
              return function() {
                if (_this.canSeal()) {
                  return Object.isSealed(_object);
                } else {
                  return false;
                }
              };
            })(this);
            this.canPreventExtensions = (function(_this) {
              return function() {
                return typeof Object.preventExtensions === 'function';
              };
            })(this);
            this.isExtensible = (function(_this) {
              return function() {
                if (_this.canPreventExtensions()) {
                  return Object.isExtensible(_object);
                } else {
                  return true;
                }
              };
            })(this);
            this.preventExtensions = (function(_this) {
              return function() {
                if (_this.canPreventExtensions()) {
                  Object.preventExtensions(_this);
                  Object.preventExtensions(_object);
                }
                return _this;
              };
            })(this);
            _mdRef = {};
            if (!(this instanceof _metaData)) {
              if (!((arguments.length > 2) && ((_mdRef = arguments[2]) != null) instanceof _metaData)) {
                _mdRef = new _metaData(this, {
                  _path: "",
                  _root: this
                });
              } else {
                _mdRef = arguments[2];
              }
              this.objectID = (function(_this) {
                return function() {
                  return _mdRef.get('_id');
                };
              })(this);
              this.root = (function(_this) {
                return function() {
                  var ref1;
                  return (ref1 = _mdRef.root()) != null ? ref1 : _this;
                };
              })(this);
              this.path = (function(_this) {
                return function() {
                  return _mdRef.path();
                };
              })(this);
              this.parent = (function(_this) {
                return function() {
                  var ref1;
                  return (ref1 = _mdRef.parent()) != null ? ref1 : _this;
                };
              })(this);
            }
          }
        
          return Schema;
        
        })();
        
        _metaData = (function() {
          function _metaData(_oRef, _data) {
            var _cName, _id;
            _cName = _global.wf.wfUtils.Fun.getConstructorName(_oRef);
            if (this._createID == null) {
              _id = 0;
              _metaData.prototype._createID = function() {
                if (this.__objID == null) {
                  this.__objID = "" + _cName + (_id + 1);
                }
                return this.__objID;
              };
            }
            Object.assign(_data, {
              _id: this._createID(),
              _className: _cName,
              _created: Date.now()
            });
            this.get = (function(_this) {
              return function(key) {
                var ref;
                return (ref = _data[key]) != null ? ref : null;
              };
            })(this);
            this.set = (function(_this) {
              return function() {
                return "not implemented";
              };
            })(this);
            this.objectID = (function(_this) {
              return function() {
                return _this.get('_id');
              };
            })(this);
            this.root = (function(_this) {
              return function() {
                return _this.get('_root');
              };
            })(this);
            this.path = (function(_this) {
              return function() {
                return _this.get('_path');
              };
            })(this);
            this.parent = (function(_this) {
              return function() {
                var _p;
                _p = (_p = _this.path().split('.')).length > 1 ? _p.slice(0, _p.length - 2).join('.') : _p[0];
                if (_p.length > 0) {
                  return _this.root().get(_p);
                } else {
                  return _this;
                }
              };
            })(this);
          }
        
          return _metaData;
        
        })();
        
    var _sKeys, _schemaroller_;
    _schemaroller_ = new SchemaRoller;
    _schemaroller_.registerClass('Schema', _schemaroller_.Schema = Schema);
    _schemaroller_.registerClass('Vector', _schemaroller_.Vector = Vector);
    _sKeys = Object.keys(_schemaroller_.getSchemaRef());
    if (_schemaroller_.rx == null) {
      _schemaroller_.rx = new RegExp("^((" + (_sKeys.join('|')) + ")+,?){" + _sKeys.length + "}$");
    }
    return _schemaroller_;
  };

}).call(this);
