// Generated by CoffeeScript 1.10.0
var SchemaRoller, Vector, global, objUtil,
  slice = [].slice;

global = typeof exports !== "undefined" && exports !== null ? exports : window;

objUtil = require('obj-utils');

Vector = (function() {
  'use strict';
  function Vector() {
    var _check, _list, _type, items;
    _type = arguments[0], items = 2 <= arguments.length ? slice.call(arguments, 1) : [];
    _list = [];
    if (!Array.isArray(_type)) {
      if (typeof _type === 'string') {
        _type = [_type];
      }
      if (typeof _type !== 'function') {
        _type = '*';
      }
    }
    _check = function(item) {
      if (_type === '*') {
        return true;
      }
      return objUtil.isOfType(item, _type);
    };
    this.getItemAt = (function(_this) {
      return function(idx) {
        if (_list.length = idx + 1) {
          return _list[idx];
        } else {
          return null;
        }
      };
    })(this);
    this.setItemAt = (function(_this) {
      return function(idx, item) {
        if (!_check(item)) {
          return false;
        }
        _list.splice(idx, 0, item);
        return true;
      };
    })(this);
    this.removeItemAt = (function(_this) {
      return function(idx, item) {
        if (!(idx <= _list.length)) {
          return false;
        }
        return _list.splice(idx, 1, item);
      };
    })(this);
    this.replaceItemAt = (function(_this) {
      return function(idx, item) {
        if (!_check(item)) {
          return false;
        }
        if (!(idx <= _list.length)) {
          return false;
        }
        if (idx <= _list.length) {
          return _list.splice(idx, 1);
        }
      };
    })(this);
    this.addItem = (function(_this) {
      return function(item) {
        return _this.setItemAt(_list.length, item);
      };
    })(this);
    this.shift = (function(_this) {
      return function() {
        return _list.shift();
      };
    })(this);
    this.unshift = (function(_this) {
      return function() {
        var items;
        items = 1 <= arguments.length ? slice.call(arguments, 0) : [];
        return items.forEach(function(item) {
          return _this.setItemAt(0, item);
        });
      };
    })(this);
    this.pop = (function(_this) {
      return function() {
        return _list.shift();
      };
    })(this);
    this.push = (function(_this) {
      return function() {
        var items;
        items = 1 <= arguments.length ? slice.call(arguments, 0) : [];
        return items.forEach(function(item) {
          return _this.addItem(item);
        });
      };
    })(this);
    this.reset = (function(_this) {
      return function() {
        return _list = [];
      };
    })(this);
    this.length = (function(_this) {
      return function() {
        return _list.length;
      };
    })(this);
    this.sort = (function(_this) {
      return function(func) {
        return _list.sort(func);
      };
    })(this);
    this.values = (function(_this) {
      return function() {
        return _list.values();
      };
    })(this);
    this.toString = (function(_this) {
      return function() {
        return _list.toString();
      };
    })(this);
    if (items != null) {
      this.push(items);
    }
  }

  return Vector;

})();

SchemaRoller = (typeof module !== "undefined" && module !== null ? module.parent.exports : void 0) ? module.parent.exports.SchemaRoller : require('schemaroller');

SchemaRoller.registerClass("Vector", Vector);

module.exports = Vector;
